### ISSUE TITLE
[Image upload]

### ISSUE THREAD

**Issue by grabbou** [grabbou/react-native-touchable-bounce#1]
![ezgif-936384229](https://cloud.githubusercontent.com/assets/2464966/13904982/de81a4ae-eeb2-11e5-93d5-797ba1758a23.gif)

**Comment by Noitidart** [comment]
Is this a typical style on iOS or Android? I can't find where is used.

**Comment by grabbou** [comment]
It's not, for that use `TouchableNativeFeedback`. This is when you neeed bouncing.

**Comment by Noitidart** [comment]
Thanks @grabbou for your comment. I didn't know where else to ask. I was surprised to see this component, I was reading .56 release notes and came across this.
